import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1>TrainerKelly's Japanese Learning Session</h1>
          <nav className="section-nav">
            <Link id="home-btn" className="section-links nav-link" href="/">
              Home
            </Link>
            <Link
              id="about-btn"
              className="section-links nav-link"
              href="/about"
            >
              About
            </Link>
            <Link
              id="settings-btn"
              className="section-links nav-link"
              href="/settings"
            >
              Word List &amp; Settings
            </Link>
            <Link
              id="word-selection-btn"
              className="section-links nav-link"
              href="/selection"
            >
              Word Selection
            </Link>
            <Link
              id="learn-btn"
              className="section-links nav-link"
              href="/learn"
            >
              Learn
            </Link>
            <Link
              id="credits-btn"
              className="section-links nav-link"
              href="/credits"
            >
              Credits
            </Link>
          </nav>
        </header>
        <main>{children}</main>
        <footer>
          <p>
            Site created by{" "}
            <Link href="https://www.kellymulry.com" target="_blank">
              Kelly Mulry
            </Link>
            . For personal use.
          </p>
        </footer>
      </body>
    </html>
  );
}
